### ISSUE TITLE
OSX Compatibility

### ISSUE THREAD

**Issue by endel** [alexeiskachykhin/flc#1]
Hi @alexeiskachykhin, thanks for your work here. Looks great stuff.

Couldn't get it working on OSX though. Is this tool currently working only on Windows?

Cheers,
Endel

**Comment by alexeiskachykhin** [comment]
Hi @endel, thank you for submitting an issue. Yes, currently it is tested only on Windows. Since you expressed an interest to have it working on OSX I will take a look into it on this week-end.

Could you please let me know what version of OSX and Adobe Flash Pro you use?

**Comment by endel** [comment]
Hey @alexeiskachykhin, thanks for your quick reply :) 

I'm using OSX 10.11.4, and Adobe Animate CC 2015.2.

Cheers!

**Comment by alexeiskachykhin** [comment]
@endel I wanted to give you an update on this issue. I fixed an issue that prevented flc from run on OSX. Please get the latest version from npm. At least now you should be able to run `flc -h`. I'm not sure about compilation functionality, I'm looking into right it now. This is what I'm going to do in next couple of days:
- Allow flc to work properly without administrative permissions (this is required because I observe licensing issues with Adobe Animate when run under super user).
- Check end to end that compilation works.
